---
title: "P-model: Latest Versions"
# author: "Koen Hufkens"
output: 
  rmarkdown::html_vignette:
    toc-depth: 3
vignette: >
  %\VignetteIndexEntry{P-model: Latest Versions}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, include=FALSE, echo=FALSE}

#' Open Tasks:
#' - One could compare the outputs of the most recent and second recent version
#'   directly. Could be done by comparing all metrics in the outputed table and
#'   create a new table showing percentual changes.
#'   
#' - eval_sofun() returns large objects (~200 Mb) because the nested ggplots holds
#'   replicates the input data, blowing up its size. Instead, eval_sofun() could only
#'   return the relevant plots, or the run_latest_versions() could do that.
```

This vignette pulls the latest three releases of the {rsofun} package and runs the same analysis using the same input data. Thereby, this vignettes allows to keep track of changes in model performance associated with updates to {rsofun}.

```{r warning=FALSE, message=FALSE, error=FALSE, include = FALSE}
# Install rpmodel
# if ("rpmodel" %in% installed.packages()) remove.packages("rpmodel")
devtools::install_github("geco-bern/rpmodel", upgrade = "never", force = TRUE)

# Load libraries
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(lubridate)
library(knitr)
library(ggthemes)
library(httr)
library(jsonlite)
library(here)

# Load functions
source("../R/eval_sofun.R")
source("../R/get_stats.R")
source("../R/analyse_modobs2.R")
source("../R/run_latest_versions.R")

# Set seed
set.seed(42)
```

```{r warning=FALSE, message=FALSE, error=FALSE, include = FALSE}
latest_versions <- run_latest_versions(1)
tags <- names(latest_versions)
```

## 8-daily means
```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=6, fig.height=6}
tag <- tags[1]
cat(paste0("Tag: ", tag))
latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_xdaily

# tag <- tags[2]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_xdaily
# 
# tag <- tags[3]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_xdaily
```

## Spatial - Annual
```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=6, fig.height=6}
tag <- tags[1]
cat(paste0("Tag: ", tag))
latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_spatial_annual

# tag <- tags[2]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_spatial_annual
# 
# tag <- tags[3]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$plot$gg_modobs_spatial_annual
```

##  Metrics
```{r message = FALSE, warning = FALSE, echo = FALSE}
tag <- tags[1]
cat(paste0("Tag: ", tag))
latest_versions[[tag]]$gpp$fluxnet$metrics |> 
          dplyr::bind_rows(.id = "Level") |> 
          knitr::kable()

# tag <- tags[2]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$metrics |> 
#           dplyr::bind_rows(.id = "Level") |> 
#           knitr::kable()
# 
# tag <- tags[3]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$gpp$fluxnet$metrics |> 
#           dplyr::bind_rows(.id = "Level") |> 
#           knitr::kable()
```

## Seasonal Cycles
```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=6, fig.height=6}
tag <- tags[1]
cat(paste0("Tag: ", tag))
latest_versions[[tag]]$seasonal_cycle

# tag <- tags[2]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$seasonal_cycle
# 
# tag <- tags[3]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$seasonal_cycle
```

## Drought Response
```{r message = FALSE, warning = FALSE, echo = FALSE, fig.width=6, fig.height=6}
tag <- tags[1]
cat(paste0("Tag: ", tag))
latest_versions[[tag]]$drought_response

# tag <- tags[2]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$drought_response
# 
# tag <- tags[3]
# cat(paste0("Tag: ", tag))
# latest_versions[[tag]]$drought_response
```
